This homework data set depends on this data set:

https://www.kaggle.com/yersever/500-person-gender-height-weight-bodymassindex?select=500_Person_Gender_Height_Weight_Index.csv

Please submit this homework by creating an RMD file in your project1
git repo. The RMD should run in the project1 docker environment. You
may need to install the gbm package.



* Problem 1:

Build a glm in R to classifier individuals as either Male or Female
based on their weight and height.

What is the accuracy of the model?

* Problem 2:

Use the 'gbm' package to train a similar model. Don't worry about
hyper parameter tuning for now. 

What is the accuracy of the model?

* Problem 3

Filter the data set so that it contains only 50 Male examples but all of the female examples. Create
a new model for this data set. What is the F1 Score of the model? 

* Problem 4

For the model in the previous example plot an ROC curve. What does
this ROC curve mean?

* Problem 5 

Using K-Means, cluster the same data set. Can you identify the
clusters with the known labels? Provide an interpretation of this
result.




